{"@t":"2020-06-28T16:51:15.4459624Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T16:51:41.3050965Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T16:53:17.3157695Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T16:54:43.9748804Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T16:58:25.0681321Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:01:49.5726257Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:01:50.5509315Z","@mt":"Quartz starting...","Module":"Phrases"}
{"@t":"2020-06-28T17:01:50.6201113Z","@mt":"Quartz started.","Module":"Phrases"}
{"@t":"2020-06-28T17:02:11.0929845Z","@mt":"Job DEFAULT.b7e0acfb-6079-4431-9b93-1052feeb2a0c threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.OutboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 37\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 17\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:e713a999-99eb-4609-9e7d-ac6c7c2f8b1a\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:02:11.3797224Z","@mt":"Job DEFAULT.93ad4fb3-5f4c-4dc0-a804-b2d58f57b2d5 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.InboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:36ec2ab7-82fe-4065-a287-09805c1d7ec6\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:02:11.5175170Z","@mt":"Job DEFAULT.b39a05ce-3897-4772-856c-423785fada87 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.InternalCommands'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 33\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:23160f35-50d2-4576-adc3-8ba4490d4900\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:02:15.4016805Z","@mt":"Job DEFAULT.b39a05ce-3897-4772-856c-423785fada87 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.InternalCommands'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 33\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:e713a999-99eb-4609-9e7d-ac6c7c2f8b1a\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:02:15.4862518Z","@mt":"Job DEFAULT.93ad4fb3-5f4c-4dc0-a804-b2d58f57b2d5 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.InboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:23160f35-50d2-4576-adc3-8ba4490d4900\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:02:15.5246772Z","@mt":"Job DEFAULT.b7e0acfb-6079-4431-9b93-1052feeb2a0c threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.OutboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 37\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 17\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:36ec2ab7-82fe-4065-a287-09805c1d7ec6\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:02:30.4717139Z","@mt":"Job DEFAULT.93ad4fb3-5f4c-4dc0-a804-b2d58f57b2d5 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.InboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:36ec2ab7-82fe-4065-a287-09805c1d7ec6\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:02:30.4904478Z","@mt":"Job DEFAULT.b39a05ce-3897-4772-856c-423785fada87 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.InternalCommands'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 33\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:e713a999-99eb-4609-9e7d-ac6c7c2f8b1a\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:02:30.5101205Z","@mt":"Job DEFAULT.b7e0acfb-6079-4431-9b93-1052feeb2a0c threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.OutboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 37\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 17\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:23160f35-50d2-4576-adc3-8ba4490d4900\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:02:45.3321052Z","@mt":"Job DEFAULT.93ad4fb3-5f4c-4dc0-a804-b2d58f57b2d5 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.InboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:23160f35-50d2-4576-adc3-8ba4490d4900\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:02:45.3520143Z","@mt":"Job DEFAULT.b39a05ce-3897-4772-856c-423785fada87 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.InternalCommands'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 33\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:36ec2ab7-82fe-4065-a287-09805c1d7ec6\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:02:45.4128548Z","@mt":"Job DEFAULT.b7e0acfb-6079-4431-9b93-1052feeb2a0c threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.OutboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 37\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 17\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:e713a999-99eb-4609-9e7d-ac6c7c2f8b1a\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:03:00.1566188Z","@mt":"Job DEFAULT.93ad4fb3-5f4c-4dc0-a804-b2d58f57b2d5 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.InboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:e713a999-99eb-4609-9e7d-ac6c7c2f8b1a\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:03:00.3293318Z","@mt":"Job DEFAULT.b7e0acfb-6079-4431-9b93-1052feeb2a0c threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.OutboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 37\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 17\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:36ec2ab7-82fe-4065-a287-09805c1d7ec6\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:03:00.3293905Z","@mt":"Job DEFAULT.b39a05ce-3897-4772-856c-423785fada87 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Phrase.InternalCommands'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 33\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:23160f35-50d2-4576-adc3-8ba4490d4900\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:04:32.3405627Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:04:33.4276109Z","@mt":"Quartz starting...","Module":"Phrases"}
{"@t":"2020-06-28T17:04:33.4954154Z","@mt":"Quartz started.","Module":"Phrases"}
{"@t":"2020-06-28T17:04:45.7659517Z","@mt":"Job DEFAULT.dfab0c65-e3a5-4d18-9479-8bbe8d76dca3 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Match.InternalCommands'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 33\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:60faf011-529b-4b90-8bb9-ba9abd26585f\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:04:45.8880073Z","@mt":"Job DEFAULT.b6a89a6b-0e31-478b-a0cd-e908db0c1bb0 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Match.OutboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 37\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 17\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:f36ccdd3-7015-41b8-b243-978c3c3bb1a0\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:04:46.1500912Z","@mt":"Job DEFAULT.29aa8bc8-1abe-44b9-8bf6-7fae47839a99 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Match.InboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:370edd29-4c24-4134-87d9-02f19b4288b5\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:05:00.2238346Z","@mt":"Job DEFAULT.dfab0c65-e3a5-4d18-9479-8bbe8d76dca3 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Match.InternalCommands'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 33\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:f36ccdd3-7015-41b8-b243-978c3c3bb1a0\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:05:00.3040312Z","@mt":"Job DEFAULT.b6a89a6b-0e31-478b-a0cd-e908db0c1bb0 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Match.OutboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 37\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 17\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:370edd29-4c24-4134-87d9-02f19b4288b5\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:05:00.3568409Z","@mt":"Job DEFAULT.29aa8bc8-1abe-44b9-8bf6-7fae47839a99 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Match.InboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:60faf011-529b-4b90-8bb9-ba9abd26585f\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:06:10.7694824Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:06:12.0243050Z","@mt":"Quartz starting...","Module":"Phrases"}
{"@t":"2020-06-28T17:06:12.1264983Z","@mt":"Quartz started.","Module":"Phrases"}
{"@t":"2020-06-28T17:06:15.6710429Z","@mt":"Job DEFAULT.a931555f-7fdc-4cf8-80b3-cdfd315c2738 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Match.OutboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 37\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 17\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:2778fa5f-2a87-4793-b24a-4f269efd125f\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:06:15.8731191Z","@mt":"Job DEFAULT.025f1ec1-78db-4f2e-a38c-282be6ea7695 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Match.InternalCommands'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 33\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:8785e75c-87db-482d-b436-2c60fa565c2e\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:06:15.9903469Z","@mt":"Job DEFAULT.192db0e3-e6cf-4c4f-b25a-5271725641f1 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Match.InboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:2b8c2011-e8ee-4963-94f5-fc0af4d6cf3c\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:06:30.2754550Z","@mt":"Job DEFAULT.025f1ec1-78db-4f2e-a38c-282be6ea7695 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Match.InternalCommands'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 33\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:8785e75c-87db-482d-b436-2c60fa565c2e\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:06:30.3152003Z","@mt":"Job DEFAULT.a931555f-7fdc-4cf8-80b3-cdfd315c2738 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Match.OutboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxCommandHandler.Handle(ProcessOutboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxCommandHandler.cs:line 37\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.Outbox.ProcessOutboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Outbox\\ProcessOutboxJob.cs:line 17\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:2778fa5f-2a87-4793-b24a-4f269efd125f\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:06:30.3533035Z","@mt":"Job DEFAULT.192db0e3-e6cf-4c4f-b25a-5271725641f1 threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Match.InboxMessages'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.Inbox.ProcessInboxCommandHandler.Handle(ProcessInboxCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxCommandHandler.cs:line 34\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.Inbox.ProcessInboxJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\Inbox\\ProcessInboxJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:2b8c2011-e8ee-4963-94f5-fc0af4d6cf3c\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:06:59.3540711Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:08:03.4554355Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:10:10.4099690Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:10:24.3751232Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:10:25.7382855Z","@mt":"Quartz starting...","Module":"Phrases"}
{"@t":"2020-06-28T17:10:25.7999735Z","@mt":"Quartz started.","Module":"Phrases"}
{"@t":"2020-06-28T17:14:48.0394073Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:15:34.2532170Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:15:51.1153571Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:16:14.7675008Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:25:30.1930012Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:25:31.4975241Z","@mt":"Quartz starting...","Module":"Phrases"}
{"@t":"2020-06-28T17:25:31.5593995Z","@mt":"Quartz started.","Module":"Phrases"}
{"@t":"2020-06-28T17:25:45.8159633Z","@mt":"Job DEFAULT.af880cdf-80f9-45a3-bd7b-859334272e1b threw an unhandled Exception: ","@l":"Error","@x":"System.Data.SqlClient.SqlException (0x80131904): Invalid object name 'Match.InternalCommands'.\r\n   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)\r\n   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()\r\n   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)\r\n   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 419\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsCommandHandler.Handle(ProcessInternalCommandsCommand command, CancellationToken cancellationToken) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsCommandHandler.cs:line 33\r\n   at Matches.Infrastructure.Configuration.Processing.CommandExecutor.Execute(ICommand command) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\CommandExecutor.cs:line 18\r\n   at Matches.Infrastructure.Configuration.Processing.InternalCommands.ProcessInternalCommandsJob.Execute(IJobExecutionContext context) in C:\\Users\\ryan_\\source\\repos\\FootballBanter\\Services\\Matches\\Matches.Infrastructure\\Configuration\\Processing\\InternalCommands\\ProcessInternalCommandsJob.cs:line 18\r\n   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)\r\nClientConnectionId:ef438f1d-024d-463a-8a02-ef4a93836938\r\nError Number:208,State:1,Class:16","Module":"Phrases"}
{"@t":"2020-06-28T17:26:15.7654181Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:26:16.9597760Z","@mt":"Quartz starting...","Module":"Phrases"}
{"@t":"2020-06-28T17:26:17.0256760Z","@mt":"Quartz started.","Module":"Phrases"}
{"@t":"2020-06-28T17:26:54.3400821Z","@mt":"Logger configured","Module":"API"}
{"@t":"2020-06-28T17:26:56.5859675Z","@mt":"Quartz starting...","Module":"Phrases"}
{"@t":"2020-06-28T17:26:56.6803018Z","@mt":"Quartz started.","Module":"Phrases"}
